<?php
$cfray_data = array(
    "TNR" => array(
        "iata" => "TNR",
        "city" => "Antananarivo",
        "state" => "",
        "country" => "Madagascar",
        "alpha2" => "MG",
    ),
    "AMS" => array(
        "iata" => "AMS",
        "city" => "Amsterdam",
        "state" => "",
        "country" => "Netherlands",
        "alpha2" => "NL",
    ),
    "BLR" => array(
        "iata" => "BLR",
        "city" => "Bangalore",
        "state" => "",
        "country" => "India",
        "alpha2" => "IN",
    ),
    "ARI" => array(
        "iata" => "ARI",
        "city" => "Arica",
        "state" => "",
        "country" => "Chile",
        "alpha2" => "CL",
    ),
    "AMM" => array(
        "iata" => "AMM",
        "city" => "Amman",
        "state" => "",
        "country" => "Jordan",
        "alpha2" => "JO",
    ),
    "IAD" => array(
        "iata" => "IAD",
        "city" => "Ashburn",
        "state" => "VA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "ADL" => array(
        "iata" => "ADL",
        "city" => "Adelaide",
        "state" => "SA",
        "country" => "Australia",
        "alpha2" => "AU",
    ),
    "AKL" => array(
        "iata" => "AKL",
        "city" => "Auckland",
        "state" => "",
        "country" => "New Zealand",
        "alpha2" => "NZ",
    ),
    "ATL" => array(
        "iata" => "ATL",
        "city" => "Atlanta",
        "state" => "GA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "ATH" => array(
        "iata" => "ATH",
        "city" => "Athens",
        "state" => "",
        "country" => "Greece",
        "alpha2" => "GR",
    ),
    "BKK" => array(
        "iata" => "BKK",
        "city" => "Bangkok",
        "state" => "",
        "country" => "Thailand",
        "alpha2" => "TH",
    ),
    "CAI" => array(
        "iata" => "CAI",
        "city" => "Cairo",
        "state" => "",
        "country" => "Egypt",
        "alpha2" => "EG",
    ),
    "BGW" => array(
        "iata" => "BGW",
        "city" => "Baghdad",
        "state" => "",
        "country" => "Iraq",
        "alpha2" => "IQ",
    ),
    "ASU" => array(
        "iata" => "ASU",
        "city" => "Asunción",
        "state" => "",
        "country" => "Paraguay",
        "alpha2" => "PY",
    ),
    "CPT" => array(
        "iata" => "CPT",
        "city" => "Cape Town",
        "state" => "",
        "country" => "South Africa",
        "alpha2" => "ZA",
    ),
    "CEB" => array(
        "iata" => "CEB",
        "city" => "Cebu",
        "state" => "",
        "country" => "Philippines",
        "alpha2" => "PH",
    ),
    "BNE" => array(
        "iata" => "BNE",
        "city" => "Brisbane",
        "state" => "QLD",
        "country" => "Australia",
        "alpha2" => "AU",
    ),
    "BOS" => array(
        "iata" => "BOS",
        "city" => "Boston",
        "state" => "MA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "BOG" => array(
        "iata" => "BOG",
        "city" => "Bogotá",
        "state" => "",
        "country" => "Colombia",
        "alpha2" => "CO",
    ),
    "BCN" => array(
        "iata" => "BCN",
        "city" => "Barcelona",
        "state" => "",
        "country" => "Spain",
        "alpha2" => "ES",
    ),
    "GYD" => array(
        "iata" => "GYD",
        "city" => "Baku",
        "state" => "",
        "country" => "Azerbaijan",
        "alpha2" => "AZ",
    ),
    "CTU" => array(
        "iata" => "CTU",
        "city" => "Chengdu",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "BEG" => array(
        "iata" => "BEG",
        "city" => "Belgrade",
        "state" => "",
        "country" => "Serbia",
        "alpha2" => "RS",
    ),
    "BEY" => array(
        "iata" => "BEY",
        "city" => "Beirut",
        "state" => "",
        "country" => "Lebanon",
        "alpha2" => "LB",
    ),
    "CMN" => array(
        "iata" => "CMN",
        "city" => "Casablanca",
        "state" => "",
        "country" => "Morocco",
        "alpha2" => "MA",
    ),
    "EZE" => array(
        "iata" => "EZE",
        "city" => "Buenos Aires",
        "state" => "",
        "country" => "Argentina",
        "alpha2" => "AR",
    ),
    "MEL" => array(
        "iata" => "MEL",
        "city" => "Melbourne",
        "state" => "VIC",
        "country" => "Australia",
        "alpha2" => "AU",
    ),
    "BUF" => array(
        "iata" => "BUF",
        "city" => "Buffalo",
        "state" => "NY",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "MAA" => array(
        "iata" => "MAA",
        "city" => "Chennai",
        "state" => "",
        "country" => "India",
        "alpha2" => "IN",
    ),
    "CWB" => array(
        "iata" => "CWB",
        "city" => "Curitiba",
        "state" => "",
        "country" => "Brazil",
        "alpha2" => "BR",
    ),
    "YYC" => array(
        "iata" => "YYC",
        "city" => "Calgary",
        "state" => "AB",
        "country" => "Canada",
        "alpha2" => "CA",
    ),
    "TXL" => array(
        "iata" => "TXL",
        "city" => "Berlin",
        "state" => "",
        "country" => "Germany",
        "alpha2" => "DE",
    ),
    "DOH" => array(
        "iata" => "DOH",
        "city" => "Doha",
        "state" => "",
        "country" => "Qatar",
        "alpha2" => "QA",
    ),
    "DAR" => array(
        "iata" => "DAR",
        "city" => "Dar Es Salaam",
        "state" => "",
        "country" => "Tanzania",
        "alpha2" => "TZ",
    ),
    "NOU" => array(
        "iata" => "NOU",
        "city" => "Noumea",
        "state" => "",
        "country" => "New Caledonia",
        "alpha2" => "NC",
    ),
    "DXB" => array(
        "iata" => "DXB",
        "city" => "Dubai",
        "state" => "",
        "country" => "United Arab Emirates",
        "alpha2" => "AE",
    ),
    "CGP" => array(
        "iata" => "CGP",
        "city" => "Chittagong",
        "state" => "",
        "country" => "Bangladesh",
        "alpha2" => "BD",
    ),
    "FOR" => array(
        "iata" => "FOR",
        "city" => "Fortaleza",
        "state" => "",
        "country" => "Brazil",
        "alpha2" => "BR",
    ),
    "BRU" => array(
        "iata" => "BRU",
        "city" => "Brussels",
        "state" => "",
        "country" => "Belgium",
        "alpha2" => "BE",
    ),
    "CLT" => array(
        "iata" => "CLT",
        "city" => "Charlotte",
        "state" => "NC",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "PER" => array(
        "iata" => "PER",
        "city" => "Perth",
        "state" => "WA",
        "country" => "Australia",
        "alpha2" => "AU",
    ),
    "JIB" => array(
        "iata" => "JIB",
        "city" => "Djibouti City",
        "state" => "",
        "country" => "Djibouti",
        "alpha2" => "DJ",
    ),
    "OTP" => array(
        "iata" => "OTP",
        "city" => "Bucharest",
        "state" => "",
        "country" => "Romania",
        "alpha2" => "RO",
    ),
    "ORD" => array(
        "iata" => "ORD",
        "city" => "Chicago",
        "state" => "IL",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "KWI" => array(
        "iata" => "KWI",
        "city" => "Kuwait City",
        "state" => "",
        "country" => "Kuwait",
        "alpha2" => "KW",
    ),
    "SYD" => array(
        "iata" => "SYD",
        "city" => "Sydney",
        "state" => "NSW",
        "country" => "Australia",
        "alpha2" => "AU",
    ),
    "CKG" => array(
        "iata" => "CKG",
        "city" => "Chongqing",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "DUR" => array(
        "iata" => "DUR",
        "city" => "Durban",
        "state" => "",
        "country" => "South Africa",
        "alpha2" => "ZA",
    ),
    "GUA" => array(
        "iata" => "GUA",
        "city" => "Guatemala City",
        "state" => "",
        "country" => "Guatemala",
        "alpha2" => "GT",
    ),
    "BAH" => array(
        "iata" => "BAH",
        "city" => "Manama",
        "state" => "",
        "country" => "Bahrain",
        "alpha2" => "BH",
    ),
    "LIM" => array(
        "iata" => "LIM",
        "city" => "Lima",
        "state" => "",
        "country" => "Peru",
        "alpha2" => "PE",
    ),
    "BUD" => array(
        "iata" => "BUD",
        "city" => "Budapest",
        "state" => "",
        "country" => "Hungary",
        "alpha2" => "HU",
    ),
    "CMH" => array(
        "iata" => "CMH",
        "city" => "Columbus",
        "state" => "OH",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "CMB" => array(
        "iata" => "CMB",
        "city" => "Colombo",
        "state" => "",
        "country" => "Sri Lanka",
        "alpha2" => "LK",
    ),
    "JNB" => array(
        "iata" => "JNB",
        "city" => "Johannesburg",
        "state" => "",
        "country" => "South Africa",
        "alpha2" => "ZA",
    ),
    "MDE" => array(
        "iata" => "MDE",
        "city" => "Medellín",
        "state" => "",
        "country" => "Colombia",
        "alpha2" => "CO",
    ),
    "DAC" => array(
        "iata" => "DAC",
        "city" => "Dhaka",
        "state" => "",
        "country" => "Bangladesh",
        "alpha2" => "BD",
    ),
    "MCT" => array(
        "iata" => "MCT",
        "city" => "Muscat",
        "state" => "",
        "country" => "Oman",
        "alpha2" => "OM",
    ),
    "DFW" => array(
        "iata" => "DFW",
        "city" => "Dallas",
        "state" => "TX",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "KIV" => array(
        "iata" => "KIV",
        "city" => "Chișinău",
        "state" => "",
        "country" => "Moldova",
        "alpha2" => "MD",
    ),
    "KGL" => array(
        "iata" => "KGL",
        "city" => "Kigali",
        "state" => "",
        "country" => "Rwanda",
        "alpha2" => "RW",
    ),
    "DEN" => array(
        "iata" => "DEN",
        "city" => "Denver",
        "state" => "CO",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "CPH" => array(
        "iata" => "CPH",
        "city" => "Copenhagen",
        "state" => "",
        "country" => "Denmark",
        "alpha2" => "DK",
    ),
    "SZX" => array(
        "iata" => "SZX",
        "city" => "Dongguan",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "LOS" => array(
        "iata" => "LOS",
        "city" => "Lagos",
        "state" => "",
        "country" => "Nigeria",
        "alpha2" => "NG",
    ),
    "ZDM" => array(
        "iata" => "ZDM",
        "city" => "Ramallah",
        "state" => "",
        "country" => "Palestine",
        "alpha2" => "PS",
    ),
    "PTY" => array(
        "iata" => "PTY",
        "city" => "Panama City",
        "state" => "",
        "country" => "Panama",
        "alpha2" => "PA",
    ),
    "DTW" => array(
        "iata" => "DTW",
        "city" => "Detroit",
        "state" => "MI",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "POA" => array(
        "iata" => "POA",
        "city" => "Porto Alegre",
        "state" => "",
        "country" => "Brazil",
        "alpha2" => "BR",
    ),
    "ORK" => array(
        "iata" => "ORK",
        "city" => "Cork",
        "state" => "",
        "country" => "Ireland",
        "alpha2" => "IE",
    ),
    "FUO" => array(
        "iata" => "FUO",
        "city" => "Foshan",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "LAD" => array(
        "iata" => "LAD",
        "city" => "Luanda",
        "state" => "",
        "country" => "Angola",
        "alpha2" => "AO",
    ),
    "RUH" => array(
        "iata" => "RUH",
        "city" => "Riyadh",
        "state" => "",
        "country" => "Saudi Arabia",
        "alpha2" => "SA",
    ),
    "FOC" => array(
        "iata" => "FOC",
        "city" => "Fuzhou",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "HNL" => array(
        "iata" => "HNL",
        "city" => "Honolulu",
        "state" => "HI",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "UIO" => array(
        "iata" => "UIO",
        "city" => "Quito",
        "state" => "",
        "country" => "Ecuador",
        "alpha2" => "EC",
    ),
    "MPM" => array(
        "iata" => "MPM",
        "city" => "Maputo",
        "state" => "",
        "country" => "Mozambique",
        "alpha2" => "MZ",
    ),
    "TLV" => array(
        "iata" => "TLV",
        "city" => "Tel Aviv",
        "state" => "",
        "country" => "Israel",
        "alpha2" => "IL",
    ),
    "DUB" => array(
        "iata" => "DUB",
        "city" => "Dublin",
        "state" => "",
        "country" => "Ireland",
        "alpha2" => "IE",
    ),
    "CAN" => array(
        "iata" => "CAN",
        "city" => "Guangzhou",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "IAH" => array(
        "iata" => "IAH",
        "city" => "Houston",
        "state" => "TX",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "GIG" => array(
        "iata" => "GIG",
        "city" => "Rio de Janeiro",
        "state" => "",
        "country" => "Brazil",
        "alpha2" => "BR",
    ),
    "DUS" => array(
        "iata" => "DUS",
        "city" => "Düsseldorf",
        "state" => "",
        "country" => "Germany",
        "alpha2" => "DE",
    ),
    "MBA" => array(
        "iata" => "MBA",
        "city" => "Mombasa",
        "state" => "",
        "country" => "Kenya",
        "alpha2" => "KE",
    ),
    "MRU" => array(
        "iata" => "MRU",
        "city" => "Port Louis",
        "state" => "",
        "country" => "Mauritius",
        "alpha2" => "MU",
    ),
    "EDI" => array(
        "iata" => "EDI",
        "city" => "Edinburgh",
        "state" => "",
        "country" => "United Kingdom",
        "alpha2" => "GB",
    ),
    "GRU" => array(
        "iata" => "GRU",
        "city" => "São Paulo",
        "state" => "",
        "country" => "Brazil",
        "alpha2" => "BR",
    ),
    "IND" => array(
        "iata" => "IND",
        "city" => "Indianapolis",
        "state" => "IN",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "HGH" => array(
        "iata" => "HGH",
        "city" => "Hangzhou",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "HAN" => array(
        "iata" => "HAN",
        "city" => "Hanoi",
        "state" => "",
        "country" => "Vietnam",
        "alpha2" => "VN",
    ),
    "FRA" => array(
        "iata" => "FRA",
        "city" => "Frankfurt",
        "state" => "",
        "country" => "Germany",
        "alpha2" => "DE",
    ),
    "JAX" => array(
        "iata" => "JAX",
        "city" => "Jacksonville",
        "state" => "FL",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "RUN" => array(
        "iata" => "RUN",
        "city" => "Réunion",
        "state" => "",
        "country" => "France",
        "alpha2" => "FR",
    ),
    "SCL" => array(
        "iata" => "SCL",
        "city" => "Santiago",
        "state" => "",
        "country" => "Chile",
        "alpha2" => "CL",
    ),
    "GVA" => array(
        "iata" => "GVA",
        "city" => "Geneva",
        "state" => "",
        "country" => "Switzerland",
        "alpha2" => "CH",
    ),
    "MCI" => array(
        "iata" => "MCI",
        "city" => "Kansas City",
        "state" => "MO",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "CUR" => array(
        "iata" => "CUR",
        "city" => "Willemstad",
        "state" => "",
        "country" => "Curaçao",
        "alpha2" => "CW",
    ),
    "HNY" => array(
        "iata" => "HNY",
        "city" => "Hengyang",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "LAS" => array(
        "iata" => "LAS",
        "city" => "Las Vegas",
        "state" => "NV",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "SGN" => array(
        "iata" => "SGN",
        "city" => "Ho Chi Minh City",
        "state" => "",
        "country" => "Vietnam",
        "alpha2" => "VN",
    ),
    "GOT" => array(
        "iata" => "GOT",
        "city" => "Gothenburg",
        "state" => "",
        "country" => "Sweden",
        "alpha2" => "SE",
    ),
    "GND" => array(
        "iata" => "GND",
        "city" => "St. George's",
        "state" => "",
        "country" => "Grenada",
        "alpha2" => "GD",
    ),
    "LAX" => array(
        "iata" => "LAX",
        "city" => "Los Angeles",
        "state" => "CA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "HAM" => array(
        "iata" => "HAM",
        "city" => "Hamburg",
        "state" => "",
        "country" => "Germany",
        "alpha2" => "DE",
    ),
    "HKG" => array(
        "iata" => "HKG",
        "city" => "Hong Kong",
        "state" => "",
        "country" => "Hong Kong",
        "alpha2" => "HK",
    ),
    "HYD" => array(
        "iata" => "HYD",
        "city" => "Hyderabad",
        "state" => "",
        "country" => "India",
        "alpha2" => "IN",
    ),
    "HEL" => array(
        "iata" => "HEL",
        "city" => "Helsinki",
        "state" => "",
        "country" => "Finland",
        "alpha2" => "FI",
    ),
    "MFE" => array(
        "iata" => "MFE",
        "city" => "McAllen",
        "state" => "TX",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "ISB" => array(
        "iata" => "ISB",
        "city" => "Islamabad",
        "state" => "",
        "country" => "Pakistan",
        "alpha2" => "PK",
    ),
    "MEM" => array(
        "iata" => "MEM",
        "city" => "Memphis",
        "state" => "TN",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "IST" => array(
        "iata" => "IST",
        "city" => "Istanbul",
        "state" => "",
        "country" => "Turkey",
        "alpha2" => "TR",
    ),
    "CGK" => array(
        "iata" => "CGK",
        "city" => "Jakarta",
        "state" => "",
        "country" => "Indonesia",
        "alpha2" => "ID",
    ),
    "KBP" => array(
        "iata" => "KBP",
        "city" => "Kyiv",
        "state" => "",
        "country" => "Ukraine",
        "alpha2" => "UA",
    ),
    "MEX" => array(
        "iata" => "MEX",
        "city" => "Mexico City",
        "state" => "",
        "country" => "Mexico",
        "alpha2" => "MX",
    ),
    "TNA" => array(
        "iata" => "TNA",
        "city" => "Jinan",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "MIA" => array(
        "iata" => "MIA",
        "city" => "Miami",
        "state" => "FL",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "LIS" => array(
        "iata" => "LIS",
        "city" => "Lisbon",
        "state" => "",
        "country" => "Portugal",
        "alpha2" => "PT",
    ),
    "LHR" => array(
        "iata" => "LHR",
        "city" => "London",
        "state" => "",
        "country" => "United Kingdom",
        "alpha2" => "GB",
    ),
    "KHI" => array(
        "iata" => "KHI",
        "city" => "Karachi",
        "state" => "",
        "country" => "Pakistan",
        "alpha2" => "PK",
    ),
    "MSP" => array(
        "iata" => "MSP",
        "city" => "Minneapolis",
        "state" => "MN",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "LUX" => array(
        "iata" => "LUX",
        "city" => "Luxembourg City",
        "state" => "",
        "country" => "Luxembourg",
        "alpha2" => "LU",
    ),
    "MGM" => array(
        "iata" => "MGM",
        "city" => "Montgomery",
        "state" => "AL",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "KTM" => array(
        "iata" => "KTM",
        "city" => "Kathmandu",
        "state" => "",
        "country" => "Nepal",
        "alpha2" => "NP",
    ),
    "CCU" => array(
        "iata" => "CCU",
        "city" => "Kolkata",
        "state" => "",
        "country" => "India",
        "alpha2" => "IN",
    ),
    "MAD" => array(
        "iata" => "MAD",
        "city" => "Madrid",
        "state" => "",
        "country" => "Spain",
        "alpha2" => "ES",
    ),
    "YUL" => array(
        "iata" => "YUL",
        "city" => "Montréal",
        "state" => "QC",
        "country" => "Canada",
        "alpha2" => "CA",
    ),
    "KUL" => array(
        "iata" => "KUL",
        "city" => "Kuala Lumpur",
        "state" => "",
        "country" => "Malaysia",
        "alpha2" => "MY",
    ),
    "BNA" => array(
        "iata" => "BNA",
        "city" => "Nashville",
        "state" => "TN",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "MAN" => array(
        "iata" => "MAN",
        "city" => "Manchester",
        "state" => "",
        "country" => "United Kingdom",
        "alpha2" => "GB",
    ),
    "MRS" => array(
        "iata" => "MRS",
        "city" => "Marseille",
        "state" => "",
        "country" => "France",
        "alpha2" => "FR",
    ),
    "EWR" => array(
        "iata" => "EWR",
        "city" => "Newark",
        "state" => "NJ",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "LHE" => array(
        "iata" => "LHE",
        "city" => "Lahore",
        "state" => "",
        "country" => "Pakistan",
        "alpha2" => "PK",
    ),
    "ORF" => array(
        "iata" => "ORF",
        "city" => "Norfolk",
        "state" => "VA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "MXP" => array(
        "iata" => "MXP",
        "city" => "Milan",
        "state" => "",
        "country" => "Italy",
        "alpha2" => "IT",
    ),
    "NAY" => array(
        "iata" => "NAY",
        "city" => "Langfang",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "LYA" => array(
        "iata" => "LYA",
        "city" => "Luoyang",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "DME" => array(
        "iata" => "DME",
        "city" => "Moscow",
        "state" => "",
        "country" => "Russia",
        "alpha2" => "RU",
    ),
    "OMA" => array(
        "iata" => "OMA",
        "city" => "Omaha",
        "state" => "NE",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "PHL" => array(
        "iata" => "PHL",
        "city" => "Philadelphia",
        "state" => "",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "MFM" => array(
        "iata" => "MFM",
        "city" => "Macau",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "MUC" => array(
        "iata" => "MUC",
        "city" => "Munich",
        "state" => "",
        "country" => "Germany",
        "alpha2" => "DE",
    ),
    "MLE" => array(
        "iata" => "MLE",
        "city" => "Malé",
        "state" => "",
        "country" => "Maldives",
        "alpha2" => "MV",
    ),
    "PHX" => array(
        "iata" => "PHX",
        "city" => "Phoenix",
        "state" => "AZ",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "LCA" => array(
        "iata" => "LCA",
        "city" => "Nicosia",
        "state" => "",
        "country" => "Cyprus",
        "alpha2" => "CY",
    ),
    "PIT" => array(
        "iata" => "PIT",
        "city" => "Pittsburgh",
        "state" => "PA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "MNL" => array(
        "iata" => "MNL",
        "city" => "Manila",
        "state" => "",
        "country" => "Philippines",
        "alpha2" => "PH",
    ),
    "OSL" => array(
        "iata" => "OSL",
        "city" => "Oslo",
        "state" => "",
        "country" => "Norway",
        "alpha2" => "NO",
    ),
    "CDG" => array(
        "iata" => "CDG",
        "city" => "Paris",
        "state" => "",
        "country" => "France",
        "alpha2" => "FR",
    ),
    "BOM" => array(
        "iata" => "BOM",
        "city" => "Mumbai",
        "state" => "",
        "country" => "India",
        "alpha2" => "IN",
    ),
    "PAP" => array(
        "iata" => "PAP",
        "city" => "Port-Au-Prince",
        "state" => "",
        "country" => "Haiti",
        "alpha2" => "HT",
    ),
    "PDX" => array(
        "iata" => "PDX",
        "city" => "Portland",
        "state" => "OR",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "NAG" => array(
        "iata" => "NAG",
        "city" => "Nagpur",
        "state" => "",
        "country" => "India",
        "alpha2" => "IN",
    ),
    "PRG" => array(
        "iata" => "PRG",
        "city" => "Prague",
        "state" => "",
        "country" => "Czech Republic",
        "alpha2" => "CZ",
    ),
    "QRO" => array(
        "iata" => "QRO",
        "city" => "Queretaro",
        "state" => "MX",
        "country" => "Mexico",
        "alpha2" => "MX",
    ),
    "KEF" => array(
        "iata" => "KEF",
        "city" => "Reykjavík",
        "state" => "",
        "country" => "Iceland",
        "alpha2" => "IS",
    ),
    "NNG" => array(
        "iata" => "NNG",
        "city" => "Nanning",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "RIC" => array(
        "iata" => "RIC",
        "city" => "Richmond",
        "state" => "VA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "RIX" => array(
        "iata" => "RIX",
        "city" => "Riga",
        "state" => "",
        "country" => "Latvia",
        "alpha2" => "LV",
    ),
    "DEL" => array(
        "iata" => "DEL",
        "city" => "New Delhi",
        "state" => "",
        "country" => "India",
        "alpha2" => "IN",
    ),
    "SMF" => array(
        "iata" => "SMF",
        "city" => "Sacramento",
        "state" => "CA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "KIX" => array(
        "iata" => "KIX",
        "city" => "Osaka",
        "state" => "",
        "country" => "Japan",
        "alpha2" => "JP",
    ),
    "FCO" => array(
        "iata" => "FCO",
        "city" => "Rome",
        "state" => "",
        "country" => "Italy",
        "alpha2" => "IT",
    ),
    "LED" => array(
        "iata" => "LED",
        "city" => "Saint Petersburg",
        "state" => "",
        "country" => "Russia",
        "alpha2" => "RU",
    ),
    "SLC" => array(
        "iata" => "SLC",
        "city" => "Salt Lake City",
        "state" => "UT",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "PNH" => array(
        "iata" => "PNH",
        "city" => "Phnom Penh",
        "state" => "",
        "country" => "Cambodia",
        "alpha2" => "KH",
    ),
    "SAN" => array(
        "iata" => "SAN",
        "city" => "San Diego",
        "state" => "CA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "TAO" => array(
        "iata" => "TAO",
        "city" => "Qingdao",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "SOF" => array(
        "iata" => "SOF",
        "city" => "Sofia",
        "state" => "",
        "country" => "Bulgaria",
        "alpha2" => "BG",
    ),
    "SJC" => array(
        "iata" => "SJC",
        "city" => "San Jose",
        "state" => "CA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "ARN" => array(
        "iata" => "ARN",
        "city" => "Stockholm",
        "state" => "",
        "country" => "Sweden",
        "alpha2" => "SE",
    ),
    "ICN" => array(
        "iata" => "ICN",
        "city" => "Seoul",
        "state" => "",
        "country" => "South Korea",
        "alpha2" => "KR",
    ),
    "SHA" => array(
        "iata" => "SHA",
        "city" => "Shanghai",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "TLL" => array(
        "iata" => "TLL",
        "city" => "Tallinn",
        "state" => "",
        "country" => "Estonia",
        "alpha2" => "EE",
    ),
    "YXE" => array(
        "iata" => "YXE",
        "city" => "Saskatoon",
        "state" => "SK",
        "country" => "Canada",
        "alpha2" => "CA",
    ),
    "SKG" => array(
        "iata" => "SKG",
        "city" => "Thessaloniki",
        "state" => "",
        "country" => "Greece",
        "alpha2" => "GR",
    ),
    "SEA" => array(
        "iata" => "SEA",
        "city" => "Seattle",
        "state" => "WA",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "SHE" => array(
        "iata" => "SHE",
        "city" => "Shenyang",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "STL" => array(
        "iata" => "STL",
        "city" => "St. Louis",
        "state" => "MO",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "VIE" => array(
        "iata" => "VIE",
        "city" => "Vienna",
        "state" => "",
        "country" => "Austria",
        "alpha2" => "AT",
    ),
    "SJW" => array(
        "iata" => "SJW",
        "city" => "Shijiazhuang",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "VNO" => array(
        "iata" => "VNO",
        "city" => "Vilnius",
        "state" => "",
        "country" => "Lithuania",
        "alpha2" => "LT",
    ),
    "SIN" => array(
        "iata" => "SIN",
        "city" => "Singapore",
        "state" => "",
        "country" => "Singapore",
        "alpha2" => "SG",
    ),
    "TPA" => array(
        "iata" => "TPA",
        "city" => "Tampa",
        "state" => "FL",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "YYZ" => array(
        "iata" => "YYZ",
        "city" => "Toronto",
        "state" => "ON",
        "country" => "Canada",
        "alpha2" => "CA",
    ),
    "WAW" => array(
        "iata" => "WAW",
        "city" => "Warsaw",
        "state" => "",
        "country" => "Poland",
        "alpha2" => "PL",
    ),
    "SZV" => array(
        "iata" => "SZV",
        "city" => "Suzhou",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "TPE" => array(
        "iata" => "TPE",
        "city" => "Taipei",
        "state" => "",
        "country" => "Taiwan",
        "alpha2" => "TW",
    ),
    "ZAG" => array(
        "iata" => "ZAG",
        "city" => "Zagreb",
        "state" => "",
        "country" => "Croatia",
        "alpha2" => "HR",
    ),
    "YVR" => array(
        "iata" => "YVR",
        "city" => "Vancouver",
        "state" => "BC",
        "country" => "Canada",
        "alpha2" => "CA",
    ),
    "TLH" => array(
        "iata" => "TLH",
        "city" => "Tallahassee",
        "state" => "FL",
        "country" => "United States",
        "alpha2" => "US",
    ),
    "ZRH" => array(
        "iata" => "ZRH",
        "city" => "Zürich",
        "state" => "",
        "country" => "Switzerland",
        "alpha2" => "CH",
    ),
    "PBH" => array(
        "iata" => "PBH",
        "city" => "Thimphu",
        "state" => "",
        "country" => "Bhutan",
        "alpha2" => "BT",
    ),
    "YWG" => array(
        "iata" => "YWG",
        "city" => "Winnipeg",
        "state" => "MB",
        "country" => "Canada",
        "alpha2" => "CA",
    ),
    "TSN" => array(
        "iata" => "TSN",
        "city" => "Tianjin",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "NRT" => array(
        "iata" => "NRT",
        "city" => "Tokyo",
        "state" => "",
        "country" => "Japan",
        "alpha2" => "JP",
    ),
    "ULN" => array(
        "iata" => "ULN",
        "city" => "Ulaanbaatar",
        "state" => "",
        "country" => "Mongolia",
        "alpha2" => "MN",
    ),
    "WUH" => array(
        "iata" => "WUH",
        "city" => "Wuhan",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "WUX" => array(
        "iata" => "WUX",
        "city" => "Wuxi",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "XIY" => array(
        "iata" => "XIY",
        "city" => "Xi'an",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "EVN" => array(
        "iata" => "EVN",
        "city" => "Yerevan",
        "state" => "",
        "country" => "Armenia",
        "alpha2" => "AM",
    ),
    "CGO" => array(
        "iata" => "CGO",
        "city" => "Zhengzhou",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
    "CSX" => array(
        "iata" => "CSX",
        "city" => "Zuzhou",
        "state" => "",
        "country" => "China",
        "alpha2" => "CN",
    ),
);